# Generated by Django 6.1 on 2026-08-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PlanName", models.CharField(max_length=70)),
                ("Description", models.TextField(null=True)),
                ("Prescriptions", models.TextField(null=True)),
                ("Price", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ClinicName", models.CharField(max_length=70)),
                ("ClinicAddress", models.TextField()),
                (
                    "TreatmentPlans",
                    models.ManyToManyField(to="appointment.treatmentplan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PatientName", models.CharField(max_length=70)),
                ("PatientEmail", models.EmailField(max_length=254)),
                ("PatientPhone", models.CharField(max_length=15)),
                ("AppointmentDate", models.DateTimeField()),
                (
                    "TreatmentPlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.treatmentplan",
                    ),
                ),
            ],
        ),
    ]
